### ISSUE TITLE
Why are you using a Helical antanna?

### ISSUE THREAD

**Issue by E3V3A** [FOULAB/Project-COGSWORTH#1]
Awesome project! 

But I'm a bit puzzled as to why you decided to use a Helical antenna design for your Wifi Telescope? 

AFAIK, Helical antenna designs are primarily used for Circularly polarized radiation, which again are mostly used by SatCom and intranet broadcasting. I believe you would get far better results by using a dish, also as the radiation pattern for helical's are awful in comparison to the much cleaner and focused ones for dishes.

**Comment by elff1493** [comment]
a dish is not directional enough I believe, Helical antenna has a smaller amount they can see so its better for getting one pixel without interference

**Comment by Danukeru** [comment]
Because we could build it out of crap laying around.

Simple as that.

**Comment by E3V3A** [comment]
LoL!

![dishgraveyard 1](https://user-images.githubusercontent.com/194392/45023111-5750ed00-b025-11e8-9ca9-9509132d20e1.png)
