### ISSUE TITLE
Where are the printable parts

### ISSUE THREAD

**Issue by quarinteen** [FOULAB/Project-COGSWORTH#12]
I have been trying to find the parts for this to print but cant find them. Do you have a 3d stl for this project?

**Comment by Danukeru** [comment]
There was only a set of old Mendel generation 3D printer feed gears used. 
Easily reproduced parametrically.
To be more precise they were Herringbone gears. Probably the only interesting thing about them.
Aside from that everything else was CNC/hand cut and glue gunned from hand made PVC sheets made from flattening PVC pipe with a heatgun.

**Comment by Danukeru** [comment]
Here is a set almost identical to what we used
https://www.thingiverse.com/thing:10707
